/*
 * The MIT License
 *
 * Copyright 2017 Denis Karev.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package com.calc.main.ui;

/**
 *
 * @author Денис
 */
public class CalcUI extends javax.swing.JFrame {

    double num1;
    double num2;
    double result;
    String GradRad;
    /**
     * Creates new form CalcUI
     */
    public CalcUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        num1Label = new javax.swing.JLabel();
        num1Text = new javax.swing.JTextField();
        num2Label = new javax.swing.JLabel();
        num2Text = new javax.swing.JTextField();
        operatorsLabel = new javax.swing.JLabel();
        plusButton = new javax.swing.JButton();
        minusButton = new javax.swing.JButton();
        slashButton = new javax.swing.JButton();
        starButton = new javax.swing.JButton();
        powButton = new javax.swing.JButton();
        sqrButton = new javax.swing.JButton();
        resultLabel = new javax.swing.JLabel();
        resultTextBlocked = new javax.swing.JTextField();
        creditLabel = new javax.swing.JLabel();
        clearButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        logButton = new javax.swing.JButton();
        log10Button = new javax.swing.JButton();
        sinButton = new javax.swing.JButton();
        cosButton = new javax.swing.JButton();
        tanButton = new javax.swing.JButton();
        cotButton = new javax.swing.JButton();
        arcsinButton = new javax.swing.JButton();
        arccosButton = new javax.swing.JButton();
        arctanButton = new javax.swing.JButton();
        arccotButton = new javax.swing.JButton();
        helpButton = new javax.swing.JButton();
        secButton = new javax.swing.JButton();
        cosecButton = new javax.swing.JButton();
        arcsecButton = new javax.swing.JButton();
        arccosecButton = new javax.swing.JButton();
        hsinButton = new javax.swing.JButton();
        hcosButton = new javax.swing.JButton();
        htanButton1 = new javax.swing.JButton();
        hcotButton = new javax.swing.JButton();
        hsecButton = new javax.swing.JButton();
        hcosecButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("SimpleCalc by Actis"));

        num1Label.setText("Первое число");

        num1Text.setToolTipText("Любое число");

        num2Label.setText("Второе число");

        num2Text.setToolTipText("В тригонометрических функциях здесь нужно поставить парматры grad или rad.");

        operatorsLabel.setText("Действия");

        plusButton.setText("Сложение");
        plusButton.setToolTipText("a + b");
        plusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusButtonActionPerformed(evt);
            }
        });

        minusButton.setText("Вычитание");
        minusButton.setToolTipText("a - b");
        minusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minusButtonActionPerformed(evt);
            }
        });

        slashButton.setText("Деление");
        slashButton.setToolTipText("a - b");
        slashButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                slashButtonActionPerformed(evt);
            }
        });

        starButton.setText("Умножение");
        starButton.setToolTipText("a * b");
        starButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                starButtonActionPerformed(evt);
            }
        });

        powButton.setText("Возведение");
        powButton.setToolTipText("a^b");
        powButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                powButtonActionPerformed(evt);
            }
        });

        sqrButton.setText("Корень");
        sqrButton.setToolTipText("a^(1/b)");
        sqrButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sqrButtonActionPerformed(evt);
            }
        });

        resultLabel.setText("Результат");

        resultTextBlocked.setEditable(false);

        creditLabel.setForeground(new java.awt.Color(0, 0, 204));
        creditLabel.setText("Denis Karev 2008-2017. Лицензия MIT.");

        clearButton.setText("Очистить");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        exitButton.setText("Выйти");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        logButton.setText("log");
        logButton.setToolTipText("log(a)");
        logButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logButtonActionPerformed(evt);
            }
        });

        log10Button.setText("log10");
        log10Button.setToolTipText("log10(a)");
        log10Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                log10ButtonActionPerformed(evt);
            }
        });

        sinButton.setText("sin");
        sinButton.setToolTipText("sin(a) ");
        sinButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sinButtonActionPerformed(evt);
            }
        });

        cosButton.setText("cos");
        cosButton.setToolTipText("cos(a)");
        cosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cosButtonActionPerformed(evt);
            }
        });

        tanButton.setText("tan");
        tanButton.setToolTipText("tan(a)");
        tanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanButtonActionPerformed(evt);
            }
        });

        cotButton.setText("cot");
        cotButton.setToolTipText("cot(a)");
        cotButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cotButtonActionPerformed(evt);
            }
        });

        arcsinButton.setText("arcsin");
        arcsinButton.setToolTipText("arcsin(a)");
        arcsinButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arcsinButtonActionPerformed(evt);
            }
        });

        arccosButton.setText("arccos");
        arccosButton.setToolTipText("arccos(a)");
        arccosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arccosButtonActionPerformed(evt);
            }
        });

        arctanButton.setText("arctan");
        arctanButton.setToolTipText("arctan(a)");
        arctanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arctanButtonActionPerformed(evt);
            }
        });

        arccotButton.setText("arccot");
        arccotButton.setToolTipText("arccot(a)");
        arccotButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arccotButtonActionPerformed(evt);
            }
        });

        helpButton.setText("Help");
        helpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpButtonActionPerformed(evt);
            }
        });

        secButton.setText("sec");
        secButton.setToolTipText("sin(a) ");
        secButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secButtonActionPerformed(evt);
            }
        });

        cosecButton.setText("cosec");
        cosecButton.setToolTipText("sin(a) ");
        cosecButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cosecButtonActionPerformed(evt);
            }
        });

        arcsecButton.setText("arcsec");
        arcsecButton.setToolTipText("arccot(a)");
        arcsecButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arcsecButtonActionPerformed(evt);
            }
        });

        arccosecButton.setText("arccosec");
        arccosecButton.setToolTipText("arccot(a)");
        arccosecButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arccosecButtonActionPerformed(evt);
            }
        });

        hsinButton.setText("hsin");
        hsinButton.setToolTipText("arccot(a)");
        hsinButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hsinButtonActionPerformed(evt);
            }
        });

        hcosButton.setText("hcos");
        hcosButton.setToolTipText("arccot(a)");
        hcosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hcosButtonActionPerformed(evt);
            }
        });

        htanButton1.setText("htan");
        htanButton1.setToolTipText("arccot(a)");
        htanButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                htanButton1ActionPerformed(evt);
            }
        });

        hcotButton.setText("hcot");
        hcotButton.setToolTipText("arccot(a)");
        hcotButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hcotButtonActionPerformed(evt);
            }
        });

        hsecButton.setText("hsec");
        hsecButton.setToolTipText("arccot(a)");
        hsecButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hsecButtonActionPerformed(evt);
            }
        });

        hcosecButton.setText("hcosec");
        hcosecButton.setToolTipText("arccot(a)");
        hcosecButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hcosecButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(num1Text)
                    .addComponent(num2Text, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(resultTextBlocked, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(creditLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 186, Short.MAX_VALUE)
                        .addComponent(helpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clearButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(hsinButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sinButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(powButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(arcsinButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(mainPanelLayout.createSequentialGroup()
                                    .addComponent(arccosButton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(arctanButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addComponent(sqrButton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(logButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(tanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(cosButton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(hcosButton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(htanButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cotButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(arccotButton, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(secButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(arcsecButton, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cosecButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(arccosecButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(hcotButton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hsecButton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(hcosecButton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(operatorsLabel)
                            .addComponent(num2Label)
                            .addComponent(num1Label)
                            .addComponent(resultLabel)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(plusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(slashButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(minusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(starButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGap(323, 323, 323)
                                .addComponent(log10Button, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(num1Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(num1Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(num2Label)
                .addGap(1, 1, 1)
                .addComponent(num2Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(operatorsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(plusButton)
                    .addComponent(slashButton)
                    .addComponent(minusButton)
                    .addComponent(starButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sqrButton)
                    .addComponent(log10Button)
                    .addComponent(powButton)
                    .addComponent(logButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sinButton)
                    .addComponent(cosButton)
                    .addComponent(tanButton)
                    .addComponent(cotButton)
                    .addComponent(secButton)
                    .addComponent(cosecButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(arcsinButton)
                    .addComponent(arccosButton)
                    .addComponent(arctanButton)
                    .addComponent(arccotButton)
                    .addComponent(arcsecButton)
                    .addComponent(arccosecButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hsinButton)
                    .addComponent(hcosButton)
                    .addComponent(htanButton1)
                    .addComponent(hcotButton)
                    .addComponent(hsecButton)
                    .addComponent(hcosecButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(resultLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resultTextBlocked, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(creditLabel)
                    .addComponent(clearButton)
                    .addComponent(exitButton)
                    .addComponent(helpButton)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void plusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusButtonActionPerformed
        num1 = Double.parseDouble(num1Text.getText());
        num2 = Double.parseDouble(num2Text.getText());
        result = num1 + num2;
        resultTextBlocked.setText(String.valueOf(result));
    }//GEN-LAST:event_plusButtonActionPerformed

    private void minusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minusButtonActionPerformed
        num1 = Double.parseDouble(num1Text.getText());
        num2 = Double.parseDouble(num2Text.getText());
        result = num1 - num2;
        resultTextBlocked.setText(String.valueOf(result));
    }//GEN-LAST:event_minusButtonActionPerformed

    private void slashButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_slashButtonActionPerformed
        num1 = Double.parseDouble(num1Text.getText());
        num2 = Double.parseDouble(num2Text.getText());
        result = num1 / num2;
        resultTextBlocked.setText(String.valueOf(result));       
    }//GEN-LAST:event_slashButtonActionPerformed

    private void starButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_starButtonActionPerformed
        num1 = Double.parseDouble(num1Text.getText());
        num2 = Double.parseDouble(num2Text.getText());
        result = num1 * num2;
        resultTextBlocked.setText(String.valueOf(result));
    }//GEN-LAST:event_starButtonActionPerformed

    private void powButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_powButtonActionPerformed
        num1 = Double.parseDouble(num1Text.getText());
        num2 = Double.parseDouble(num2Text.getText());
        result = Math.pow(num1, num2);
        resultTextBlocked.setText(String.valueOf(result));
    }//GEN-LAST:event_powButtonActionPerformed

    private void sqrButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sqrButtonActionPerformed
        num1 = Double.parseDouble(num1Text.getText());
        num2 = Double.parseDouble(num2Text.getText());
        result = Math.pow(num1, 1.0 /num2);
        resultTextBlocked.setText(String.valueOf(result));
    }//GEN-LAST:event_sqrButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        num1Text.setText("");
        num2Text.setText("");
        resultTextBlocked.setText("");
    }//GEN-LAST:event_clearButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void logButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logButtonActionPerformed
        num1 = Double.parseDouble(num1Text.getText());
        num2Text.setText(String.valueOf(Math.E));
        result = Math.log(num1);
        resultTextBlocked.setText(String.valueOf(result));
    }//GEN-LAST:event_logButtonActionPerformed

    private void log10ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_log10ButtonActionPerformed
        num1 = Double.parseDouble(num1Text.getText());
        num2Text.setText("10");
        result = Math.log10(num1);
        resultTextBlocked.setText(String.valueOf(result));
    }//GEN-LAST:event_log10ButtonActionPerformed

    private void sinButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sinButtonActionPerformed
        GradRad = num2Text.getText();
        num1 = Double.parseDouble(num1Text.getText());
        switch (GradRad) {
            case "rad":
                result = Math.sin(num1);
                resultTextBlocked.setText(String.valueOf(result));
                break;
            case "grad":
                num1 = Math.toRadians(num1);
                result = Math.sin(num1);
                resultTextBlocked.setText(String.valueOf(result));
                break;
            default:
                resultTextBlocked.setText("ERROR! Используйте grad или rad в качестве второго числа!");
                break;
        }
    }//GEN-LAST:event_sinButtonActionPerformed

    private void cosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cosButtonActionPerformed
        GradRad = num2Text.getText();
        num1 = Double.parseDouble(num1Text.getText());
        switch (GradRad) {
            case "rad":
                result = Math.cos(num1);
                resultTextBlocked.setText(String.valueOf(result));
                break;
            case "grad":
                num1 = Math.toRadians(num1);
                result = Math.cos(num1);
                resultTextBlocked.setText(String.valueOf(result));
                break;
            default:
                resultTextBlocked.setText("ERROR! Используйте grad или rad в качестве второго числа!");
                break;
        }
    }//GEN-LAST:event_cosButtonActionPerformed

    private void tanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanButtonActionPerformed
         GradRad = num2Text.getText();
        num1 = Double.parseDouble(num1Text.getText());
        switch (GradRad) {
            case "rad":
                result = Math.tan(num1);
                resultTextBlocked.setText(String.valueOf(result));
                break;
            case "grad":
                num1 = Math.toRadians(num1);
                result = Math.tan(num1);
                resultTextBlocked.setText(String.valueOf(result));
                break;
            default:
                resultTextBlocked.setText("ERROR! Используйте grad или rad в качестве второго числа!");
                break;
        }
    }//GEN-LAST:event_tanButtonActionPerformed

    private void cotButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cotButtonActionPerformed
        GradRad = num2Text.getText();
        num1 = Double.parseDouble(num1Text.getText());
        switch (GradRad) {
            case "rad":
                result = Math.cos(num1) / Math.sin(num1);
                resultTextBlocked.setText(String.valueOf(result));
                break;
            case "grad":
                num1 = Math.toRadians(num1);
                result = Math.cos(num1) / Math.sin(num1);
                resultTextBlocked.setText(String.valueOf(result));
                break;
            default:
                resultTextBlocked.setText("ERROR! Используйте grad или rad в качестве второго числа!");
                break;
        }
    }//GEN-LAST:event_cotButtonActionPerformed

    private void arcsinButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arcsinButtonActionPerformed
        GradRad = num2Text.getText();
        num1 = Double.parseDouble(num1Text.getText());
        switch (GradRad) {
            case "rad":
                result = Math.asin(num1);
                resultTextBlocked.setText(String.valueOf(result));
                break;
            case "grad":
                result = Math.asin(num1);
                result = Math.toDegrees(result);
                resultTextBlocked.setText(String.valueOf(result));
                break;
            default:
                resultTextBlocked.setText("ERROR! Используйте grad или rad в качестве второго числа!");
                break;
        }
    }//GEN-LAST:event_arcsinButtonActionPerformed

    private void arccosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arccosButtonActionPerformed
        GradRad = num2Text.getText();
        num1 = Double.parseDouble(num1Text.getText());
        switch (GradRad) {
            case "rad":
                result = Math.acos(num1);
                resultTextBlocked.setText(String.valueOf(result));
                break;
            case "grad":
                result = Math.acos(num1);
                result = Math.toDegrees(result);
                resultTextBlocked.setText(String.valueOf(result));
                break;
            default:
                resultTextBlocked.setText("ERROR! Используйте grad или rad в качестве второго числа!");
                break;
        }
    }//GEN-LAST:event_arccosButtonActionPerformed

    private void arctanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arctanButtonActionPerformed
        GradRad = num2Text.getText();
        num1 = Double.parseDouble(num1Text.getText());
        switch (GradRad) {
            case "rad":
                result = Math.atan(num1);
                resultTextBlocked.setText(String.valueOf(result));
                break;
            case "grad":
                result = Math.atan(num1);
                result = Math.toDegrees(result);
                resultTextBlocked.setText(String.valueOf(result));
                break;
            default:
                resultTextBlocked.setText("ERROR! Используйте grad или rad в качестве второго числа!");
                break;
        }
    }//GEN-LAST:event_arctanButtonActionPerformed

    private void arccotButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arccotButtonActionPerformed
        GradRad = num2Text.getText();
        num1 = Double.parseDouble(num1Text.getText());
        switch (GradRad) {
            case "rad":
                result = Math.acos(num1) / Math.asin(num1);
                resultTextBlocked.setText(String.valueOf(result));
                break;
            case "grad":
                result = Math.acos(num1) / Math.asin(num1);
                result = Math.toDegrees(result);
                resultTextBlocked.setText(String.valueOf(result));
                break;
            default:
                resultTextBlocked.setText("ERROR! Используйте grad или rad в качестве второго числа!");
                break;
        }
    }//GEN-LAST:event_arccotButtonActionPerformed

    private void helpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpButtonActionPerformed
        HelpUI helpdialog = new HelpUI();
        helpdialog.setVisible (true);
    }//GEN-LAST:event_helpButtonActionPerformed

    private void secButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_secButtonActionPerformed

    private void cosecButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cosecButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cosecButtonActionPerformed

    private void arcsecButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arcsecButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_arcsecButtonActionPerformed

    private void arccosecButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arccosecButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_arccosecButtonActionPerformed

    private void hsinButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hsinButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hsinButtonActionPerformed

    private void hcosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hcosButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hcosButtonActionPerformed

    private void htanButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_htanButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_htanButton1ActionPerformed

    private void hcotButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hcotButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hcotButtonActionPerformed

    private void hsecButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hsecButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hsecButtonActionPerformed

    private void hcosecButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hcosecButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hcosecButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalcUI().setVisible(true);
            }
        });
        System.out.println("actis.pro 2014-2017. ПО распространяется по лицензии MIT");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton arccosButton;
    private javax.swing.JButton arccosecButton;
    private javax.swing.JButton arccotButton;
    private javax.swing.JButton arcsecButton;
    private javax.swing.JButton arcsinButton;
    private javax.swing.JButton arctanButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JButton cosButton;
    private javax.swing.JButton cosecButton;
    private javax.swing.JButton cotButton;
    private javax.swing.JLabel creditLabel;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton hcosButton;
    private javax.swing.JButton hcosecButton;
    private javax.swing.JButton hcotButton;
    private javax.swing.JButton helpButton;
    private javax.swing.JButton hsecButton;
    private javax.swing.JButton hsinButton;
    private javax.swing.JButton htanButton1;
    private javax.swing.JButton log10Button;
    private javax.swing.JButton logButton;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton minusButton;
    private javax.swing.JLabel num1Label;
    private javax.swing.JTextField num1Text;
    private javax.swing.JLabel num2Label;
    private javax.swing.JTextField num2Text;
    private javax.swing.JLabel operatorsLabel;
    private javax.swing.JButton plusButton;
    private javax.swing.JButton powButton;
    private javax.swing.JLabel resultLabel;
    private javax.swing.JTextField resultTextBlocked;
    private javax.swing.JButton secButton;
    private javax.swing.JButton sinButton;
    private javax.swing.JButton slashButton;
    private javax.swing.JButton sqrButton;
    private javax.swing.JButton starButton;
    private javax.swing.JButton tanButton;
    // End of variables declaration//GEN-END:variables
}
